export { default as Homepage } from './Homepage'
export { default as Dashboard } from './Dashboard'
export { default as CreateEvent } from './CreateEvent'
export { default as CreateOutline } from './ProgrammeOutline/CreateOutline'
export { default as GenerateLink } from './ProgrammeOutline/GenerateLink'
export { default as Events } from './Events'
export { default as Event } from './Event'
export { default as EventHomepage } from './EventRegistration/EventHomepage'
export { default as RegistrationSuccess } from './EventRegistration/RegistrationSuccess'
// export { default as Homepage } from './Homepage'